apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp-copilot-desafio-04
  labels:
    app: desafio-04
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio-04
  template:
    metadata:
      labels:
        app: desafio-04
    spec:
      containers:
      - name: exp-copilot-desafio-04
        image: jrsmarcilio/exp-copilot-desafio-04
        ports:
        - containerPort: 3000